### ISSUE TITLE
Cannot register a token from an Android device

### ISSUE THREAD

**Issue by ptmkenny** [signalpoint/push_notifications#10]
I have an Android device running Android 2.3.4 that I am using to attempt to test push notifications.

I have set my GCM_SENDER_ID in push_notifications.js.

My understanding is that when I log in to my site using the app, a push notification should be registered.  However, no token is registered, although no error message is given.

From debugging with the console, I see that when calling push_notifications_register(), when it gets to:

```
    pushNotification.register(push_notifications_successHandler, push_notifications_errorHandler, {"senderID": GCM_SENDER_ID, "ecb": "onNotification"});
```

then push_notifications_errorHandler() is called, and the content of the error is **java.lang.Long**.  onNotification(e) (which is the next step in the process if things are going well, right?) is not called.  Unfortunately I'm at a loss of how to debug this further, so I would really appreciate any help you could provide.

**Comment by ptmkenny** [comment]
In the Android emulator (which I understand I can use to test push notifications if I log in using a Google account, which I have done), I get this slightly more verbose error message:

**push_notifications_errorHandler - java.lang.Long cannot be cast to java.lang.String**

**Comment by DefiantBidet** [comment]
i had the same error. i made the value of that variable a string (read: wrapped my GCMSenderID in quotes) that error is gone, but it still does not register a device. edit: i had otehr issues that caused failure to register.  i am able to register a device... debugging why it doesn't send. but that's not relevant to this issue... `var GCM_SENDER_ID = 'ID_HERE';` works

**Comment by tolesolo** [comment]
maybe same with my issued, 
there is no token registered at admin/config/services/push_notifications
i already login via android app, compiling with adobe air with its plugin

please let me know if someone knew how to fix it. thank you

**Comment by tolesolo** [comment]
fixed my issued, working perfectly

**Comment by mkinnan** [comment]
@tolesolo How did you solve the issue? I am having the same issue where no token is registered.

**Comment by signalpoint** [comment]
@mkinnan Make sure users have permission to create a token.

**Comment by signalpoint** [comment]
@mkinnan Also right now it's only programmed for authenticated users: https://github.com/signalpoint/push_notifications/blob/7.x-1.x/push_notifications.js#L41

**Comment by mkinnan** [comment]
@signalpoint I have set permissions in the Drupal website as such:

![push-permissions](https://cloud.githubusercontent.com/assets/13283396/13545194/eef930a0-e240-11e5-8af9-79671f669900.PNG)

**Comment by tolesolo** [comment]
@mkinnan, sorry for late response. I did something with drupalgap's custom modules, push_notification.js

Try { push_notification_register(); } on the event deviceready()

And I made 1 user role, and this role work as a clone role of authenticated role.

**Comment by mkinnan** [comment]
@tolesolo If I understand you correctly, you added the following to the end of the **push_notification.js** file , right?

```
/**
 * Implements hook_deviceready().
 */
function push_notifications_deviceready() {
  try {
    push_notifications_register();
  }
  catch (error) { console.log('push_notifications_deviceready - ' + error); }
}
```

I unchecked and rechecked the permissions at **admin/people/permissions**.
I have cleared cached.
I have rebuilt all permissions at admin/reports/status/rebuild.

**Comment by signalpoint** [comment]
@mkinnan Make sure `debug` is set to `true` in the `settings.js` file and then run this terminal command in a separate terminal tab before you've launched and compiled to Android: `adb shell logcat | grep 'CONSOLE'`

That _should_ let you see the URLs that the app is trying to hit on the Drupal site. You should see it at least attempt to contact the push notification resource in Drupal. If not, check out watchdog logs and/or php error logs.

I think what @tolesolo is saying is that they implemented `hook_deviceready` in their own module, and made a call to push_notifications_register() in there. But I don't think that is required anymore because the updates to `push_notifications.js` should register the token upon system connect.

**Comment by tolesolo** [comment]
@mkinnan, what version npm or cordova?

**Comment by signalpoint** [comment]
FYI, when I finally got push notifications to work (just a few weeks ago). I was using the latest version of Cordova 5.

**Comment by mkinnan** [comment]
@signalpoint I am using Adobe Phonegap Build to compile the app (Android and iOS). I need to figure out how to compile locally, but Adobe works really well.

@tolesolo @signalpoint I am using Android 4.1.1 (cli-5.2.0) in Adobe Phonegap Build to compile my app.

**Comment by signalpoint** [comment]
@mkinnan I'm on Ubuntu 14, and with the DG docs (I refer to them all the time) it's easy to compile an app and launch it to a device connected through USB. Mac is also pretty nice, I just wish I had a better one. As for Windows, it's been about 6 years since I've had it, but hopefully there is a nodejs/cordova msdos commands you can run (or through that popular terminal emulator, I forget its name). You could also make a partition on a drive that have dual OS. Fun times.

**Comment by tolesolo** [comment]
@mkinnan good you on the right track
 first, please try to send notification all in your drupal, /admin/config/services/push_notifications/message
let see what happen, are there notification sent to any registered token
if yes, then no problem with your cordova plugin and module push notification too

If not, I want you to check this two files, 
-- in my config.xml , I use this plugin
`<gap:plugin name="cordova-plugin-push-notification " source="npm" />`
--in my app/modules/custom/push_notifications/push_notifications.js, please write the quote string before and after GCM_SENDER_ID, GCM SENDER_ID consists of numbers only
// This needs to be set to your GCM Sender ID.
`var GCM_SENDER_ID = '1111112321113322';`

**Comment by mkinnan** [comment]
@tolesolo @signalpoint ... FINALLY got this working ... at least I can see devices registered and can send a test message from my Drupal website! In my config.xml file, had to use this plugin
`<gap:plugin name="com.devicepush.cordova-phonegap" source="npm" />`
which is listed here:
https://www.npmjs.com/package/com.devicepush.cordova-phonegap

It appears the
`<gap:plugin name="cordova-plugin-push-notification " source="npm" />`
doesn't exist anymore or is deprecated. I got errors trying to use it.

I am confused about
`var GCM_SENDER_ID = '1111112321113322';`
Is that just supposed to be at the top of the **push_notifications.js** file? How is that different than adding the sender ID to the **settings.js** file?

**Comment by mkinnan** [comment]
Here is the error I get using the plugin in my config.xml:
`<gap:plugin name="cordova-plugin-push-notification " source="npm" />`

`Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "cordova-plugin-push-notification" via npm Installing "cordova-plugin-push-notification" at "2.5.2" for android Notice: android.support.v4 has been automatically converted to cordova-android-support-v4 and fetched from npm. This is due to our old plugins registry shutting down. Fetching plugin "https://github.com/zckrs/cordova-plugin-android-support-v4.git" via git clone Repository "https://github.com/zckrs/cordova-plugin-android-support-v4.git" checked out to git ref "master" at "0ba24b8". Failed to install 'cordova-plugin-push-notification':Error: Expected plugin to have ID "cordova-android-support-v4" but got "android.support.v4". at checkID (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/fetch.js:181:15) at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/fetch.js:166:9 at _fulfilled (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54) at self.promiseDispatch.done (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30) at Promise.promise.promiseDispatch (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/node_modules/cordova-common/node_modules/q/q.js:796:13) at /home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/node_modules/cordova-common/node_modules/q/q.js:604:44 at runSingle (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/node_modules/cordova-common/node_modules/q/q.js:137:13) at flush (/home/ec2-user/.npm/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/node_modules/cordova-common/node_modules/q/q.js:125:13) at doNTCallback0 (node.js:417:9) at process._tickCallback (node.js:346:13) Expected plugin to have ID "cordova-android-support-v4" but got "android.support.v4".`

**Comment by signalpoint** [comment]
@mkinnan Are you using the latest `push_notifications.js` file? `var GCM_SENDER_ID` is now long gone.

**Comment by mkinnan** [comment]
@signalpoint Yes, I am using the latest file ... which explains why I am not seeing `var GCM_SENDER_ID`. Thanks for clarifying.

**Comment by tolesolo** [comment]
So, the UID's token has been registered. If the notification was not delireved to your app, then the issued is from the plugin.

**Comment by mkinnan** [comment]
@tolesolo Yes, tokens are getting registered. The issue was the plugin needed in config.xml file.

Thanks for the help!
